### ISSUE TITLE
Can't install from Arch Linux AUR

### ISSUE THREAD

**Issue by stardiviner** [felixonmars/fcitx5-pinyin-zhwiki#10]
I run command `yay -S fcitx5-pinyin-zhwiki`
Got error:
```
yay -S fcitx5-pinyin-zhwiki
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  fcitx5-pinyin-zhwiki-20200601-1

  1 fcitx5-pinyin-zhwiki             (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: PKGBUILD up to date, Skipping (1/1): fcitx5-pinyin-zhwiki
  1 fcitx5-pinyin-zhwiki             (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: Parsing SRCINFO (1/1): fcitx5-pinyin-zhwiki
  1 fcitx5-pinyin-zhwiki             (Build Files Exist)
==> PKGBUILDs to edit?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
==> Making package: fcitx5-pinyin-zhwiki 20200601-1 (Sat 20 Jun 2020 09:27:00 AM CST)
==> Retrieving sources...
  -> Found fcitx5-pinyin-zhwiki-0.2.1.tar.gz
  -> Found zhwiki-20200601-all-titles-in-ns0.gz
==> Validating source files with md5sums...
    fcitx5-pinyin-zhwiki-0.2.1.tar.gz ... Passed
    zhwiki-20200601-all-titles-in-ns0.gz ... Passed
==> Making package: fcitx5-pinyin-zhwiki 20200601-1 (Sat 20 Jun 2020 09:27:01 AM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found fcitx5-pinyin-zhwiki-0.2.1.tar.gz
  -> Found zhwiki-20200601-all-titles-in-ns0.gz
==> Validating source files with md5sums...
    fcitx5-pinyin-zhwiki-0.2.1.tar.gz ... Passed
    zhwiki-20200601-all-titles-in-ns0.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting fcitx5-pinyin-zhwiki-0.2.1.tar.gz with bsdtar
  -> Extracting zhwiki-20200601-all-titles-in-ns0.gz with gzip
==> Starting prepare()...
==> Sources are ready.
==> Making package: fcitx5-pinyin-zhwiki 20200601-1 (Sat 20 Jun 2020 09:27:04 AM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
gzip -k -d zhwiki-20200601-all-titles-in-ns0.gz
./zhwiki-web-slang.py > web-slang.source
Traceback (most recent call last):
  File "/usr/lib64/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib64/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/usr/lib64/python3.8/http/client.py", line 1402, in connect
    super().connect()
  File "/usr/lib64/python3.8/http/client.py", line 917, in connect
    self.sock = self._create_connection(
  File "/usr/lib64/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib64/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./zhwiki-web-slang.py", line 11, in <module>
    page = urllib.request.urlopen(_ZHWIKI_SOURCE_URL + urllib.parse.quote(_PAGE)).read()
  File "/usr/lib64/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib64/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
make: *** [Makefile:14: web-slang.source] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
Error making: fcitx5-pinyin-zhwiki
```

I have installed dependecny:
```
sudo pacman -S --noconfirm libime opencc
```
And
```
pip install -U opencc pypinyin
```

**Comment by stardiviner** [comment]
And I also tried to add shell `proxy_http` etc environment variable to my proxy. Still not work.

**Comment by stardiviner** [comment]
I manually installed by specify proxy environment variable `http_proxy`.
