### ISSUE TITLE
Cannot Build.

### ISSUE THREAD

**Issue by Firestar-Reimu** [felixonmars/fcitx5-pinyin-zhwiki#17]
```
gzip -k -d zhwiki-20201101-all-titles-in-ns0.gz
./zhwiki-web-slang.py > web-slang.source
Traceback (most recent call last):
  File "/home/firestar/.anaconda/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/firestar/.anaconda/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/firestar/.anaconda/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/firestar/.anaconda/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/firestar/.anaconda/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/home/firestar/.anaconda/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/home/firestar/.anaconda/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/home/firestar/.anaconda/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/home/firestar/.anaconda/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/home/firestar/.anaconda/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./zhwiki-web-slang.py", line 11, in <module>
    page = urllib.request.urlopen(_ZHWIKI_SOURCE_URL + urllib.parse.quote(_PAGE)).read()
  File "/home/firestar/.anaconda/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/firestar/.anaconda/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/firestar/.anaconda/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/firestar/.anaconda/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/firestar/.anaconda/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/firestar/.anaconda/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
make: *** [Makefile:14：web-slang.source] 错误 1
==> 错误： 在 build() 中发生一个错误。
    正在放弃...

```

**Comment by Firestar-Reimu** [comment]
This happens when I run `yay -S fcitx5-pinyin-zhwiki`

**Comment by felixonmars** [comment]
You need to be able to access `zh.wikipedia.org` for web slang generation.

**Comment by Firestar-Reimu** [comment]
```
$ yay -S fcitx5-pinyin-zhwiki
正在解析依赖关系...
正在查找软件包冲突...

软件包 (1) fcitx5-pinyin-zhwiki-20201101-1

下载大小：  16.95 MiB
全部安装大小：  41.81 MiB

:: 进行安装吗？ [Y/n] y
:: 正在获取软件包......
正在初始化下载：https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/x86_64/fcitx5-pinyin-zhwiki-20201101-1-any.pkg.tar.zst
File size: 17776857 bytes
正在打开输出文件 /var/cache/pacman/pkg/fcitx5-pinyin-zhwiki-20201101-1-any.pkg.tar.zst.part
正在开始下载

连接 2 完成下载
连接 5 完成下载
连接 6 完成下载
连接 10 完成下载
连接 11 完成下载
连接 12 完成下载
连接 0 完成下载
连接 1 完成下载
连接 3 完成下载
连接 8 完成下载
连接 9 完成下载
连接 14 被异常中断
连接 4 完成下载
连接 7 完成下载
连接 13 完成下载

已下载 16.9533 兆字节，用时 2 second(s)。（8211.70 KB/s）
(1/1) 正在检查密钥环里的密钥                         [----------------------------] 100%
(1/1) 正在检查软件包完整性                           [----------------------------] 100%
(1/1) 正在加载软件包文件                             [----------------------------] 100%
(1/1) 正在检查文件冲突                               [----------------------------] 100%
(1/1) 正在检查可用存储空间                           [----------------------------] 100%
:: 正在处理软件包的变化...
(1/1) 正在安装 fcitx5-pinyin-zhwiki                  [----------------------------] 100%
:: 正在运行事务后钩子函数...
(1/1) Arming ConditionNeedsUpdate...
(base) [11:17:18] firestar:~ $ 
```
It didn't build, can it be used now?
